=== malikabrar1897/Bookstore/Bookstore.dtd
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, author, year, price)>
<!ATTLIST book category CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== malikabrar1897/Bookstore/Malikabrar/Bookstore.xml
<?xml version="1.0"?>
<!DOCTYPE bookstore SYSTEM "Bookstore.dtd">
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="bookstore.xsd">

    <book>
        <title>Java</title>
        <author>Abrar</author>
        <price>500</price>
    </book>

    <book>
        <title>Python</title>
        <author>John</author>
        <price>600</price>
    </book>

</bookstore>
